language: python

# Use the new container-based Travis infrastructure.
sudo: false

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  pip

# Try OS X.
os:
  - linux
  # - osx

env:
   # shorten logging of pip-accel
   # - PIP_ACCEL_LOG_FORMAT="%(name)-18s %(levelname)s %(message)s"

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

matrix:
  allow_failures:
      # Just tests how Menus performs with upcoming Python 3.6
      - python: "nightly"
      # Ignore failures from OS X.
      - os: osx


install:
  # Install PyEnv
  - export PATH="/home/travis/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash

  - pip install tox-travis coveralls
  - pip install -r requirements.txt

script:
  - tox

after_success:
  coveralls
